package newpackage;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


 //* @author junio
 
public class Entry extends javax.swing.JFrame {

   
    public Entry() {
        initComponents();
        this.setLocationRelativeTo(null);//placed it on the center
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Login = new javax.swing.JTextField();
        jPasswordField_passwordlogin = new javax.swing.JPasswordField();
        jButton_Cancelation = new javax.swing.JButton();
        jButton2_Login = new javax.swing.JButton();
        jTextRegister = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(108, 122, 137));

        jLabelClose.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("x");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please login");

        jLabelMin.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMin))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(118, 93, 105));

        jLabel4.setBackground(new java.awt.Color(55, 55, 55));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(228, 241, 254));
        jLabel4.setText("Password : ");

        jLabel5.setBackground(new java.awt.Color(55, 55, 55));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(228, 241, 254));
        jLabel5.setText("Email :");

        jTextField_Login.setBackground(new java.awt.Color(1, 50, 67));
        jTextField_Login.setForeground(new java.awt.Color(228, 241, 254));
        jTextField_Login.setText("enter email...");
        jTextField_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LoginActionPerformed(evt);
            }
        });

        jPasswordField_passwordlogin.setBackground(new java.awt.Color(1, 50, 67));
        jPasswordField_passwordlogin.setForeground(new java.awt.Color(228, 241, 254));
        jPasswordField_passwordlogin.setText("AAAAAAAAAAAAA");

        jButton_Cancelation.setBackground(new java.awt.Color(217, 30, 24));
        jButton_Cancelation.setText("CANCEL");
        jButton_Cancelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelationActionPerformed(evt);
            }
        });

        jButton2_Login.setBackground(new java.awt.Color(1, 50, 67));
        jButton2_Login.setText("LOGIN");
        jButton2_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_LoginActionPerformed(evt);
            }
        });

        jTextRegister.setText("Sign in!!");
        jTextRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextRegisterMouseClicked(evt);
            }
        });
        jTextRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField_passwordlogin))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jButton_Cancelation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addComponent(jButton2_Login))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(46, 46, 46)
                                .addComponent(jTextField_Login))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jTextRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField_passwordlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancelation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LoginActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jButton2_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_LoginActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps,ps1,ps2,ps3,ps4,ps5,ps6;
        ResultSet rs,rs1,rs2,rs3,rs4,rs5,rs6;
        
        String useremail = jTextField_Login.getText();
        String userpass = String.valueOf(jPasswordField_passwordlogin.getPassword());
       // boolean username;
        
       /*Orizoume gia na elegxoume die3grapseta den tha ta xrisimopoihseis*/
        String a = "editor-in-chief";
        String b = "journalist";
        String c = "Secretary";
        String d = "Logistics";
        
       
        
        String query = "SELECT * FROM `employee` WHERE `email`=? AND `employee`.`password`=?";//den xrisimopoieite
        String query1 = "SELECT j_specialty FROM `journalist` inner join `employee` on `j_email` = `email` WHERE `email`=? AND `employee`.`password`=?";//gia thn 1h if na ksexorisoume journalist apo administative
        String query2 = "SELECT admin_duties FROM `administrative` inner join `employee` on `admin_email` = `email` WHERE `email`=? AND `employee`.`password`=?";//to idio gia thn 1h if
        String query3 = "SELECT j_specialty FROM `journalist`WHERE `journalist`.`j_email`=? AND `journalist`.`j_specialty` = ?";//gia thn 2h if
        String query4 = "SELECT admin_duties FROM `administrative`WHERE `administrative`.`admin_email`=? AND `administrative`.`admin_duties` = ?"; // episis gia thn deuteri pairnoume tis enum antistixa kai apo ti dio ontoties tou isa
        String query5 = "SELECT name FROM `journalist` inner join `employee` on `j_email` = `email` WHERE `journalist`.`j_email`=? "; // episis gia thn deuteri pairnoume tis enum antistixa kai apo ti dio ontoties tou isa

        
        try {
           
            
            /*pairname antistixes select an einai journalist i administrative*/
            ps1 = Myconnection.ConnectDb().prepareStatement(query1);
            ps2 = Myconnection.ConnectDb().prepareStatement(query2);
           
            
            
           /* Xrisima strings gia na perasoume tis time gia tn elegxo twn stixiwn*/
            ps1.setString(1, useremail);
            ps1.setString(2, userpass);
            ps2.setString(1, useremail);
            ps2.setString(2, userpass);
            
           /*Ekteloume tis entoles se Sql*/
            rs1 = ps1.executeQuery();
            rs2 = ps2.executeQuery();
            
            
            /*Opoia apo tis dio einai true (auto to epistrefei oi next() mpainei sthn if )*/
            
            if(rs1.next()){
                  
                
                /*Akolouthoume thn idia diadikasia gia editor in chief kai journalist kai kateuthinotai stis ekastote diepafes*/
                    ps3 = Myconnection.ConnectDb().prepareStatement(query3);
                    ps4 = Myconnection.ConnectDb().prepareStatement(query3);
                     
                    ps3.setString(1, useremail);
                    ps3.setString(2, a);
                    ps4.setString(1, useremail);
                    ps4.setString(2, b);
                        
                                        
                    rs3 = ps3.executeQuery();
                    rs4 = ps4.executeQuery();
            
                  
                            if(rs3.next()){

                                EditorInCief mf = new EditorInCief();
                                mf.setVisible(true);
                                mf.pack();
                                mf.setLocationRelativeTo(null);
                                mf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                                mf.jLabel_Arxisintaktis.setText(useremail);
                                
                                PreparedStatement ergasia_arx;
                                ResultSet apotelesma_ergasias_arx;



                                String onoma_arxisintakti = mf.jLabel_Arxisintaktis.getText();


                                String Command_for_work = "SELECT workson FROM employee WHERE email = ? ";
                              try {
                                    ergasia_arx = Myconnection.ConnectDb().prepareStatement(Command_for_work);


                                    ergasia_arx.setString(1,onoma_arxisintakti);

                                    apotelesma_ergasias_arx = ergasia_arx.executeQuery();

                                    if(apotelesma_ergasias_arx.next()) { 
                                                 String douleuei_id= apotelesma_ergasias_arx.getString("workson");
                                                mf.jLabel_Arxisintaktis_xwros_ergasias.setText(douleuei_id);
                                                System.out.println(douleuei_id);
                                       }

                                } catch (SQLException ex) {
                                    Logger.getLogger(EditorInCief.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            
  
                            }

                            else{
                               
                               
                               
                                Dimosiografos mf = new Dimosiografos();
                                mf.setVisible(true);
                                mf.pack();
                                mf.setLocationRelativeTo(null);
                                mf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                               
                                mf.jLabel_dimosiografos.setText( useremail );
                                

                                this.dispose();
                                
            
                            }
                
                
                
            }
            else if(rs2.next()) {
                   
                /*Akolouthoume thn idia diadikasia me ta dio parapanw kai ta stelnoyme stis ekastote diepafes secretery kai logistics */
                    ps5 = Myconnection.ConnectDb().prepareStatement(query4);
                    ps6 = Myconnection.ConnectDb().prepareStatement(query4);

                    ps5.setString(1, useremail);
                    ps5.setString(2, c);
                    ps6.setString(1, useremail);
                    ps6.setString(2, d);



                    rs5 = ps5.executeQuery();
                    rs6 = ps6.executeQuery();
                
                    
                        if(rs5.next()){
                            
                        
                           Administration_Secretery Secr = new Administration_Secretery();
                           Secr.setVisible(true);
                           Secr.pack();
                           Secr.setLocationRelativeTo(null);
                           Secr.setExtendedState(JFrame.MAXIMIZED_BOTH);
                           Secr.jLabel_Grammateiaemail.setText(useremail);
                           
                           
                           
                           PreparedStatement ergasia_sec;
                           ResultSet apotelesma_ergasias_sec;



                           String onoma_arxisintakti = Secr.jLabel_Grammateiaemail.getText();


                           String Command_for_work_sec = "SELECT workson FROM employee WHERE email = ? ";
                           
                           
                           
                              try {
                                    ergasia_sec = Myconnection.ConnectDb().prepareStatement(Command_for_work_sec);


                                    ergasia_sec.setString(1,onoma_arxisintakti);

                                    apotelesma_ergasias_sec = ergasia_sec.executeQuery();

                                    if(apotelesma_ergasias_sec.next()) { 
                                                 String douleuei_id= apotelesma_ergasias_sec.getString("workson");
                                                Secr.jLabel_Secretery_efimeridas.setText(douleuei_id);
                                                System.out.println(douleuei_id);
                                       }

                                } catch (SQLException ex) {
                                    Logger.getLogger(EditorInCief.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            
  

                           this.dispose();
                        }   
                        
                        else{
                        
                           Logistics enaslogistic = new Logistics();
                           enaslogistic.setVisible(true);
                           enaslogistic.pack();
                           enaslogistic.setLocationRelativeTo(null);
                           enaslogistic.setExtendedState(JFrame.MAXIMIZED_BOTH);
                           enaslogistic.jLabel_logisticseimai.setText(useremail);
                           
                           
                           
                           PreparedStatement ergasia_log;
                           ResultSet apotelesma_ergasias_log;



                           String onoma_arxisintakti = enaslogistic.jLabel_logisticseimai.getText();


                           String Command_for_work_sec = "SELECT workson FROM employee WHERE email = ? ";
                           
                           
                           
                              try {
                                    ergasia_log = Myconnection.ConnectDb().prepareStatement(Command_for_work_sec);


                                    ergasia_log.setString(1,onoma_arxisintakti);

                                    apotelesma_ergasias_log = ergasia_log.executeQuery();

                                    if(apotelesma_ergasias_log.next()) { 
                                                 String douleuei_id= apotelesma_ergasias_log.getString("workson");
                                                enaslogistic.jLabel_Logistics_efimeridas.setText(douleuei_id);
                                                System.out.println(douleuei_id);
                                       }

                                } catch (SQLException ex) {
                                    Logger.getLogger(EditorInCief.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            
  

                           this.dispose();
             
                        }
            }
            else{               
                JOptionPane.showMessageDialog(null, "Incorrect Username Or Password", "Login Failed", 2);
            }
    }
            catch (SQLException ex) {
            Logger.getLogger(Entry.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2_LoginActionPerformed

    private void jTextRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRegisterActionPerformed

    private void jTextRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextRegisterMouseClicked
        // TODO add your handling code here:
        RegisterForm rgf = new RegisterForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jTextRegisterMouseClicked

    private void jButton_CancelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelationActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_CancelationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                /* */    new Entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2_Login;
    private javax.swing.JButton jButton_Cancelation;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField_passwordlogin;
    private javax.swing.JTextField jTextField_Login;
    private javax.swing.JTextField jTextRegister;
    // End of variables declaration//GEN-END:variables
}