/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author junio
 */
public class Give_Article extends javax.swing.JFrame {

    /**
     * Creates new form Give_Article
     */
    public Give_Article() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Gianaotizeisthnseira = new javax.swing.JTextField();
        jTextField_GianaotizeisthnseiraInt = new javax.swing.JTextField();
        jButton_Done_Order = new javax.swing.JButton();
        jTextField_fillo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Give Article's Path And Order ");

        jTextField_Gianaotizeisthnseira.setBackground(new java.awt.Color(1, 50, 67));
        jTextField_Gianaotizeisthnseira.setForeground(new java.awt.Color(228, 241, 254));
        jTextField_Gianaotizeisthnseira.setText("Path..");
        jTextField_Gianaotizeisthnseira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_GianaotizeisthnseiraActionPerformed(evt);
            }
        });

        jTextField_GianaotizeisthnseiraInt.setBackground(new java.awt.Color(1, 50, 67));
        jTextField_GianaotizeisthnseiraInt.setForeground(new java.awt.Color(228, 241, 254));
        jTextField_GianaotizeisthnseiraInt.setText("Order..");
        jTextField_GianaotizeisthnseiraInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_GianaotizeisthnseiraIntActionPerformed(evt);
            }
        });

        jButton_Done_Order.setText("Done.");
        jButton_Done_Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Done_OrderActionPerformed(evt);
            }
        });

        jTextField_fillo.setBackground(new java.awt.Color(1, 50, 67));
        jTextField_fillo.setForeground(new java.awt.Color(228, 241, 254));
        jTextField_fillo.setText("Fillo..");
        jTextField_fillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_filloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(97, 97, 97))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Done_Order)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_GianaotizeisthnseiraInt, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(jTextField_fillo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTextField_Gianaotizeisthnseira, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jTextField_fillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jTextField_GianaotizeisthnseiraInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButton_Done_Order))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jTextField_Gianaotizeisthnseira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(141, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_GianaotizeisthnseiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GianaotizeisthnseiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GianaotizeisthnseiraActionPerformed

    private void jTextField_GianaotizeisthnseiraIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GianaotizeisthnseiraIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GianaotizeisthnseiraIntActionPerformed

    private void jButton_Done_OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Done_OrderActionPerformed
   
            // TODO add your handling code here:
            
            PreparedStatement Seira;
            
            
            String Path_of_article_order = jTextField_Gianaotizeisthnseira.getText();
            String order = jTextField_GianaotizeisthnseiraInt.getText();
            String filos = jTextField_fillo.getText();
            
            
            
            int order_of_article_order = Integer.parseInt(order);
            
            
            String done_it = "UPDATE `article` SET order_in_fillo = ?,publishedin = ? WHERE `PATH` = ? ";
            
      try {
            Seira = Myconnection.ConnectDb().prepareStatement(done_it);
            Seira.setInt(1, order_of_article_order);
            Seira.setString(2, filos);
            Seira.setString(3, Path_of_article_order);
            
            Seira.executeUpdate();
            
          
      } catch (SQLException ex) {
            Logger.getLogger(Give_Article.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
    }//GEN-LAST:event_jButton_Done_OrderActionPerformed

    private void jTextField_filloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_filloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_filloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Give_Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Give_Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Give_Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Give_Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Give_Article().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Done_Order;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_Gianaotizeisthnseira;
    private javax.swing.JTextField jTextField_GianaotizeisthnseiraInt;
    private javax.swing.JTextField jTextField_fillo;
    // End of variables declaration//GEN-END:variables
}
