/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author junio
 */
public class Improve_Article extends javax.swing.JFrame {

    /**
     * Creates new form Improve_Article
     */
    public Improve_Article() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Author = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_authorImp = new javax.swing.JTextField();
        jTextField_pathImpr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Catimpr = new javax.swing.JTextField();
        jTextField_PagesImpr = new javax.swing.JTextField();
        jTextField_author4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_SummImpr = new javax.swing.JTextArea();
        jDateChooser_DateImpr = new com.toedter.calendar.JDateChooser();
        jButton_Enterofart = new javax.swing.JButton();
        jButton_Cancelation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel_1.setText("Improve My Articles");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Author : ");

        jLabel_Author.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel_Author.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Author.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel_1)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Author)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_Author))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Summary :");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Title : ");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Date : ");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Path :");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Author:");

        jTextField_authorImp.setBackground(new java.awt.Color(1, 50, 67));
        jTextField_authorImp.setForeground(new java.awt.Color(228, 241, 254));
        jTextField_authorImp.setText("Author");
        jTextField_authorImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_authorImpActionPerformed(evt);
            }
        });

        jTextField_pathImpr.setBackground(new java.awt.Color(1, 50, 67));
        jTextField_pathImpr.setForeground(new java.awt.Color(228, 241, 254));
        jTextField_pathImpr.setText("Author");
        jTextField_pathImpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pathImprActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Category :");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Pages :");

        jTextField_Catimpr.setBackground(new java.awt.Color(1, 50, 67));
        jTextField_Catimpr.setForeground(new java.awt.Color(228, 241, 254));
        jTextField_Catimpr.setText("Author");
        jTextField_Catimpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CatimprActionPerformed(evt);
            }
        });

        jTextField_PagesImpr.setBackground(new java.awt.Color(1, 50, 67));
        jTextField_PagesImpr.setForeground(new java.awt.Color(228, 241, 254));
        jTextField_PagesImpr.setText("Author");
        jTextField_PagesImpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PagesImprActionPerformed(evt);
            }
        });

        jTextField_author4.setBackground(new java.awt.Color(1, 50, 67));
        jTextField_author4.setForeground(new java.awt.Color(228, 241, 254));
        jTextField_author4.setText("Author");
        jTextField_author4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_author4ActionPerformed(evt);
            }
        });

        jTextArea_SummImpr.setColumns(20);
        jTextArea_SummImpr.setRows(5);
        jScrollPane1.setViewportView(jTextArea_SummImpr);

        jDateChooser_DateImpr.setBackground(new java.awt.Color(1, 50, 67));

        jButton_Enterofart.setBackground(new java.awt.Color(1, 50, 67));
        jButton_Enterofart.setText("Improve!");
        jButton_Enterofart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EnterofartActionPerformed(evt);
            }
        });

        jButton_Cancelation.setBackground(new java.awt.Color(217, 30, 24));
        jButton_Cancelation.setText("CANCEL");
        jButton_Cancelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_Cancelation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Enterofart)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_authorImp)
                            .addComponent(jTextField_pathImpr)
                            .addComponent(jTextField_author4)
                            .addComponent(jDateChooser_DateImpr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Catimpr, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_PagesImpr, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(144, 144, 144))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_authorImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_pathImpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_author4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_Catimpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooser_DateImpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_PagesImpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Enterofart, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cancelation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_authorImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_authorImpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_authorImpActionPerformed

    private void jTextField_pathImprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pathImprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pathImprActionPerformed

    private void jTextField_CatimprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CatimprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CatimprActionPerformed

    private void jTextField_PagesImprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PagesImprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PagesImprActionPerformed

    private void jTextField_author4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_author4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_author4ActionPerformed

    private void jButton_EnterofartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EnterofartActionPerformed
        // TODO add your handling code here:

        PreparedStatement p_art_Improve, p_art_Improve1 ,elegxos;
        ResultSet elegxos_set;
        

        String author_of_article_impr = jTextField_authorImp.getText();
        String path_of_article_Impr = jTextField_pathImpr.getText();
        String title_of_article_Impr = jTextField_author4.getText();
        String summary_of_article_Impr = jTextArea_SummImpr.getText();
        String LALA = jTextField_Catimpr.getText();
        String pages_Impr = jTextField_PagesImpr.getText();

       //to email tha einai stathero den tha to prosthetei o xristis gia na min epireazei ta dedoeba allwn
        
        int category_of_article_Impr = Integer.parseInt(LALA);
        int pages_of_article_Impr = Integer.parseInt(pages_Impr);

        
        
        SimpleDateFormat DATEFORMAT_Impr = new SimpleDateFormat("yyyy-MM-dd");
        String date_of_submit = DATEFORMAT_Impr.format(jDateChooser_DateImpr.getDate());

        
        
        String S_elegxos = "SELECT * FROM submit_article WHERE sub_journalist = ? AND sub_article = ?";
        String queryins0 = "UPDATE `article` SET  title= ?, Summary= ?, artCategory= ?, pages_capacity = ?  "
                + "WHERE `article`.`Path` = ?";
      
        String queryins1 = "UPDATE `submit_article` SET sub_date = ? WHERE `sub_journalist` = ? AND `sub_article` = ?" ;
        
     
            /*  String mpampas = "UPDATE `submit_article` SET `submit_article`.`sub_date` = ?,`article`.`title` = ? "
            + ",`article`.`artCategory` = ?"
            + ",`article`.`Summary` = ?,"
            + "`article`.`pages_capacity` = ?"
            + "INNER JOIN  `article` ON `sub_article` = `Path`"
            + "WHERE `submit_article`.`sub_journalist` = ? AND `submit_article`.`sub_article` = ?";
            */
            
   try {  
            elegxos = Myconnection.ConnectDb().prepareStatement(S_elegxos);
            
            
            
            elegxos.setString(1, author_of_article_impr);
            elegxos.setString(2, path_of_article_Impr);
            
            elegxos_set = elegxos.executeQuery();
            
            
             if(  elegxos_set.next()){
                 
                 if(jTextField_authorImp.getText() == null ? jLabel_Author.getText() == null : jTextField_authorImp.getText().equals(jLabel_Author.getText())){ 
                     
            
                 try {

                    p_art_Improve = Myconnection.ConnectDb().prepareStatement(queryins0);

                    p_art_Improve.setString(1, title_of_article_Impr);
                    p_art_Improve.setString(2, summary_of_article_Impr);
                    p_art_Improve.setInt(3,  category_of_article_Impr);
                    p_art_Improve.setInt(4, pages_of_article_Impr);
                    p_art_Improve.setString(5, path_of_article_Impr);
                   // p_art_Improve.setString(6, author_of_article_impr);





                    p_art_Improve.executeUpdate();
                    
                    p_art_Improve1 = Myconnection.ConnectDb().prepareStatement(queryins1);

                    p_art_Improve1.setString(1, date_of_submit);
                    p_art_Improve1.setString(2, author_of_article_impr);
                    p_art_Improve1.setString(3,  path_of_article_Impr);

                    p_art_Improve1.executeUpdate();

               
                    

                } catch (SQLException ex) {
                    Logger.getLogger(EnterArticle.class.getName()).log(Level.SEVERE, null, ex);
                }
             }else{
                   JOptionPane.showMessageDialog(null, "No authoritie to modify this article ", "Improvement Failed", 2);
                
                }
            
                 
                 
                 
        }else{
                   JOptionPane.showMessageDialog(null, "No authoritie to modify this article ", "Improvement Failed", 2);
                
                }
            

        }catch (SQLException ex) {
                    Logger.getLogger(EnterArticle.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jButton_EnterofartActionPerformed

    private void jButton_CancelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelationActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_CancelationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Improve_Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Improve_Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Improve_Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Improve_Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Improve_Article().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelation;
    private javax.swing.JButton jButton_Enterofart;
    private com.toedter.calendar.JDateChooser jDateChooser_DateImpr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_1;
    public javax.swing.JLabel jLabel_Author;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_SummImpr;
    private javax.swing.JTextField jTextField_Catimpr;
    private javax.swing.JTextField jTextField_PagesImpr;
    private javax.swing.JTextField jTextField_author4;
    private javax.swing.JTextField jTextField_authorImp;
    private javax.swing.JTextField jTextField_pathImpr;
    // End of variables declaration//GEN-END:variables
}
